# Generated by Django 2.2.7 on 2019-11-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fio', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=128)),
                ('post_index', models.IntegerField()),
            ],
        ),
    ]
