# Generated by Django 2.2.7 on 2019-12-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191202_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Product in Order', 'verbose_name_plural': 'Products in Order'},
        ),
    ]
